# Generated by Django 4.0 on 2021-12-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_purchase_request_deivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_request',
            old_name='deivery_date',
            new_name='delivery_date',
        ),
    ]
